apiVersion: apps/v1
kind: Deployment
metadata:
  name: khaldoun-masad-deployment
  namespace: khaldoun-masad
  labels:
    app: khaldoun-masad-yolo
    env: dev
    release: v1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: khaldoun-masad-yolo
  template:
    metadata:
      labels:
        app: khaldoun-masad-yolo
        env: dev
        release: v1.0
    spec:
      containers:
      - name: khaldoun-masad-yolo-docker-container
        image: khaldoun-masad-yolo-image:tag